export { AboutUs } from './AboutUs'
export { Contact } from './Contact'
export { Credentials } from './Credentials'
//export { Home } from './Home'
export { Projects } from './Projects'
export { Services } from './Services'
export { NavBar } from './NavBar'
